name: Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: soroban
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 2222
          script: |
            echo "Remote User: ${{ secrets.REMOTE_USER }}"
            echo "SSH Key: ${{ secrets.SSH_PRIVATE_KEY }}"
            echo "trigger deploy"
